### ISSUE TITLE
FP: BAP5SQDTPP09M5B0

### ISSUE THREAD

**Issue by steviebeenz** [MSWS/NOPE#215]
# Sources
Reporter:       `CONSOLE`  
Online Players: `0`  
Owner:          `sbonthehill`  

# Plugins
```
ProtocolLib: 4.5.1
NOPE: 1.8.2
```

# Flag Log
```
Starting new log for sbonthehill (79620a2b-317c-4c8e-b90e-46dbe07e478d)
Server: Unknown Server
Server Version: git-Paper-204 (MC: 1.16.3) Bukkit: 1.16.3-R0.1-SNAPSHOT
NOPE Version: 1.8.2 (Online: null)

sbonthehill was ultimately banned for AutoSneak#1 at a VL of 2738
The actions listed for AutoSneak (Default) are:

Temporary Data Dump:

sbonthehill's flags:
Speed: 141
Spider: 206
AutoSneak: 2738

Banned sbonthehill for AutoSneak#1 2738

```

# Config
```yaml
#             ----------------------------------------------------------             
#                                                                                    
#                            NOPE Anti-Cheat Configuration                           
#                                                                                    
#               This is the configuration for NOPE. I recommend keeping              
#                the default values unless you know what you're doing.               
#                                                                                    
#                      There is a YouTube tutorial available at                      
#                     https://www.youtube.com/watch?v=XVuXKsJEAkQ                    
#                                                                                    
#                        There is a GitHub wiki tutorial also                        
#                       available at https://NOPE.MSWS.xyz/wiki                      
#                                                                                    
#             ----------------------------------------------------------             

ConfigVersion: 1.8.2
Global: true
Scoreboard: true
Log: file
GitHub:
UpdateChecker:
  Enabled: true
  InGame: true
BungeeNameOverride: ''
VLDecrement:
  Enabled: true
  Rate: 40
  Periods:
    '1000': 0
    '10000': 1
    '20000': 2
    '60000': 5
    '120000': 10
    '-1': 20
BanwaveRate: 36000
DevMode: false
DebugMode: false
Webhooks:
  banExample:
    URL: https://discordapp.com/api/webhooks/
    username: NOPE
    avatar_url: https://i.imgur.com/JLKC7CN.jpg
    embeds:
      author:
        name: '%player% Ban'
        avatar_url: https://i.imgur.com/JLKC7CN.jpg
      title: '%player% was banned for %check%'
      color: 14483456
      fields:
        check:
          name: Check
          value: '%debug%'
        world:
          name: World
          value: '%world%'
        vl:
          name: VL
          value: '%vl%'
          inline: false
  flagExample:
    URL: https://discordapp.com/api/webhooks/
    username: NOPE
    avatar_url: https://i.imgur.com/JLKC7CN.jpg
    embeds:
      author:
        name: '%player%'
        icon_url: https://crafatar.com/avatars/%uuid%
      title: '%player% flagged %check%'
      color: 751818
      fields:
        '1':
          name: Player
          value: '%player%'
        '2':
          name: World
          value: '%world%'
        '3':
          name: Server
          value: '%server%'
          inline: true
        '4':
          name: VL
          value: '%vl%'
        '5':
          name: Check
          value: '%debug%'
        '6':
          name: UUID
          value: '%uuid%'
      footer:
        text: MSWS.XYZ
Actions:
  FastBreak:
  - basiclog|cancel|vl>100|tpsdecrement|tpskick|vl>400|lagkick|tps>15|vl>600|cban
  FastClimb:
  - basiclog|vl>50|delay:1000|cancel|vl>200|cancel|vl>400|ikick|vl>600|cban
  Blink:
  - basiclog|delay:30000|cancel|vl>200|delay:2000|cancel|delay:15000|tpsdecrement|tps>15|vl>300|lagkick|vl>500|cancel|vl>800|cban
  NoSwing:
  - basiclog|vl>500|ikick|vl>1000|cban
  Speed:
  - basiclog|rndcancel|vl>100|cancel|vl>300|lagkick|vl>400|ikick|vl>800|addbanwave|vl>1200|cban
  ElytraFlight:
  - basiclog|vl>500|ikick|vl>800|addbanwave|vl>1000|cban
  Timer:
  - basiclog|vl>300|rndcancel|delay:10000|tpsdecrement|vl>500|lagkick|vl>600|ikick|vl>800|cban
  KillAura:
  - basiclog|vl>200|ikick|vl>500|delay:120000|kick:Irregular Gameplay|vl>600|cban
  NoFall:
  - basiclog|vl>300|ikick|vl>800|cban
  SafeWalk:
  - basiclog|vl>500|ikick
  AntiKB:
  - basiclog|tps>15|delay:20000|lagkick|vl>500|ikick|vl>800|cban
  Default:
  - basiclog|vl>20|cancel|vl>100|flog|vl>200|lagkick|tps>15|vl>400|ikick|vl>800|addbanwave|vl>1200|cban
Commands:
  flog: log:FILE:%player% failed %debug% (%vl%)
  alog: 'vl>100|vl<300|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed
    a &a%check%&7 check. (VL: &e%vl%&7)'
  elog: 'vl>300|vl<500|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed
    a &e%check%&7 check. (VL: &e%vl%&7)'
  clog: 'vl>500|vl<700|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player% &7failed
    a &c%check%&7 check. (VL: &e%vl%&7)'
  4log: 'vl>700|delay:500|flog|delay:60000|log:INGAME:&4&l[&c&lNOPE&4&l] &e%player%
    &7failed a &4%check%&7 check. (VL: &e%vl%&7)'
  weblog: 'notdev|vl>400|delay:120000|log:flagExample:'
  basiclog: alog|elog|clog|flog|4log|weblog
  logban: 'log:INGAME:&4&l[&c&lNOPE&4&l] &c%player% &7was banned for &b%check%&7.|log:FILE:Banned
    %player% for %debug% %vl%|delay:5000|log:banExample:'
  ikick: notdev|delay:60000|kick:Irregular Gameplay
  lagkick: ping>150|delay:20000|kick:You seem to be very laggy, please try restarting
    your connection.
  tpskick: tps<=16|delay:40000|kick:The server is extremely laggy, please try waiting
    a bit before relogging.
  tpsdecrement: tps<=16|addvl:-50
  rndcancel: rnd:.80|cancel
  canimate: |-
    logban|ban:2628000000:&4NOPE Anti-Cheat&r
    &7Token: &e%token%
  cban: notdev|delay:5000|animation:NOPE:canimate
  addbanwave: |-
    notdev|banwave:2628000000:&4NOPE Anti-Cheat&r
    &7Token: &e%token%
Checks:
  Player:
    Enabled: true
    SafeWalk:
      Enabled: true
      SafeWalk#1:
        Enabled: true
    NoFall:
      Enabled: true
      NoFall#2:
        Enabled: true
      NoFall#1:
        Enabled: true
    GhostHand:
      Enabled: true
      GhostHand#1:
        Enabled: true
    AntiFire:
      Enabled: true
      AntiFire#1:
        Enabled: true
    AutoTool:
      Enabled: true
      AutoTool#1:
        Enabled: true
    Zoot:
      Enabled: true
      Zoot#1:
        Enabled: true
    HealthTag:
      Enabled: true
      HealthTag#1:
        Enabled: true
    FastEat:
      Enabled: true
      FastEat#1:
        Enabled: true
  World:
    Enabled: true
    IllegalBlockBreak:
      Enabled: true
      IllegalBlockBreak#1:
        Enabled: true
    FastBreak:
      Enabled: true
      FastBreak#1:
        Enabled: true
    AutoBuild:
      Enabled: true
      AutoBuild#1:
        Enabled: true
    Scaffold:
      Enabled: true
      Scaffold#1:
        Enabled: true
      Scaffold#2:
        Enabled: true
    IllegalBlockPlace:
      Enabled: true
      IllegalBlockPlace#1:
        Enabled: true
  Movement:
    Enabled: true
    NoSlowDown:
      Enabled: true
      NoSlowDown#1:
        Enabled: true
      NoSlowDown#4:
        Enabled: true
      NoSlowDown#5:
        Enabled: true
      NoSlowDown#2:
        Enabled: true
      NoSlowDown#3:
        Enabled: true
    NoWeb:
      Enabled: true
      NoWeb#1:
        Enabled: true
    Flight:
      Enabled: true
      Flight#1:
        Enabled: true
      Flight#5:
        Enabled: true
      Flight#6:
        Enabled: true
      Flight#3:
        Enabled: true
      Flight#4:
        Enabled: true
      Flight#2:
        Enabled: true
    Spider:
      Enabled: true
      Spider#1:
        Enabled: true
    Jesus:
      Enabled: true
      Jesus#2:
        Enabled: true
      Jesus#1:
        Enabled: true
    InventoryMove:
      Enabled: true
      InventoryMove#1:
        Enabled: true
    Speed:
      Enabled: true
      Speed#3:
        Enabled: true
      Speed#2:
        Enabled: true
      Speed#5:
        Enabled: true
      Speed#1:
        Enabled: true
    Glide:
      Enabled: true
      Glide#1:
        Enabled: true
    FastSneak:
      Enabled: true
      FastSneak#1:
        Enabled: true
    AntiAFK:
      Enabled: true
      AntiAFK#1:
        Enabled: true
    ElytraFlight:
      Enabled: true
      ElytraFlight#1:
        Enabled: true
    BHop:
      Enabled: true
      BHop#1:
        Enabled: true
    AntiRotate:
      Enabled: true
      AntiRotate#1:
        Enabled: true
    FastClimb:
      Enabled: true
      FastClimb#1:
        Enabled: true
    AutoWalk:
      Enabled: true
      AutoWalk#1:
        Enabled: true
    ClonedMovements:
      Enabled: true
      ClonedMovement#1:
        Enabled: true
  Combat:
    Enabled: true
    FastBow:
      Enabled: true
      FastBow#1:
        Enabled: true
    KillAura:
      Enabled: true
      KillAura#2:
        Enabled: true
      KillAura#3:
        Enabled: true
      KillAura#4:
        Enabled: true
      KillAura#5:
        Enabled: true
      KillAura#1:
        Enabled: true
    HighCPS:
      Enabled: true
      HighCPS#1:
        Enabled: true
      HighCPS#3:
        Enabled: true
      HighCPS#2:
        Enabled: true
    AutoClicker:
      Enabled: true
      AutoClicker#1:
        Enabled: true
    AntiKB:
      Enabled: true
      AntiKB#1:
        Enabled: true
    AutoArmor:
      Enabled: true
      AutoArmor#1:
        Enabled: true
  Packet:
    Enabled: true
    Blink:
      Enabled: true
      Blink#1:
        Enabled: true
    NoSwing:
      Enabled: true
      NoSwing#1:
        Enabled: true
    SkinBlinker:
      Enabled: true
      SkinBlinker#1:
        Enabled: true
    Spinbot:
      Enabled: true
      Spinbot#1:
        Enabled: true
    PlayerESP:
      Enabled: true
      PlayerESP#1:
        Enabled: true
      PlayerESP#2:
        Enabled: true
    Timer:
      Enabled: true
      Timer#1:
        Enabled: true
    InvalidMovement:
      Enabled: true
      InvalidMovement#1:
        Enabled: true
    AutoSneak:
      Enabled: true
      AutoSneak#1:
        Enabled: true
```
